baseURL = 'https://blog.dogelayer.org/'
languageCode = 'en-us'
title = 'DogeLayer makes Dogecoin great again'
theme = "paper"

[params]
# color style
color = 'linen' # linen, wheat, gray, light

# header social icons
twitter = 'doge_layer' # twitter.com/YOUR_TWITTER_ID
github = 'dogelayer'   # github.com/YOUR_GITHUB_ID
# instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
# linkedin = 'YOUR_LINKEDIN_ID'   # linkedin.com/in/YOUR_LINKEDIN_ID
# mastodon = 'YOUR_MASTODON_LINK' # e.g. 'https://mastodon.instance/@xxx'
rss = true # show rss icon

# home page profile
avatar = 'wind@dogelayer.org'                   # gravatar email or image url
name = 'DogeLayer Developer Log'
bio = 'We are building the layer 2 of Dogecoin'


# misc
disableHLJS = true            # disable highlight.js
disablePostNavigation = false # disable post navigation
monoDarkIcon = true           # show monochrome dark mode icon
# gravatarCdn = 'GRAVATAR_CDN_LINK'        # e.g. 'https://cdn.v2ex.com/gravatar/'
# graphCommentId = "YOUR_GRAPH_COMMENT_ID" # use graph comment (disqus alternative)
math = true # enable KaTeX math typesetting globally
